// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WoobackVash.Api.Data;

#nullable disable

namespace WoobackVash.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721194357_AddCharacterGearAndRaidSetup")]
    partial class AddCharacterGearAndRaidSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WoobackVash.Api.Models.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("RaidEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("RaidEventId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.BoardLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RaidEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RaidEventId");

                    b.ToTable("BoardLayouts");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuildName")
                        .HasColumnType("text");

                    b.Property<int?>("GuildRank")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("GuildSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Ignored")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Realm")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SetupUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Spec")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Ignored");

                    b.HasIndex("MemberId");

                    b.HasIndex("Name");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.CharacterGearSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ItemLevel")
                        .HasColumnType("double precision");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("RaidEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Spec")
                        .HasColumnType("text");

                    b.Property<string>("WclReportCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RaidEventId");

                    b.HasIndex("CharacterId", "WclReportCode")
                        .IsUnique();

                    b.ToTable("GearSnapshots");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.LootAward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AwardedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("AwardedByMemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Checksum")
                        .HasColumnType("text");

                    b.Property<bool>("Disenchanted")
                        .HasColumnType("boolean");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<bool>("OffSpec")
                        .HasColumnType("boolean");

                    b.Property<bool>("PlusOne")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RaidEventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SoftReserve")
                        .HasColumnType("boolean");

                    b.Property<bool>("Tmb")
                        .HasColumnType("boolean");

                    b.Property<int?>("WinnerClass")
                        .HasColumnType("integer");

                    b.Property<bool>("Wishlist")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Checksum")
                        .IsUnique();

                    b.HasIndex("RaidEventId");

                    b.ToTable("LootAwards");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.LootRoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<string>("Classification")
                        .HasColumnType("text");

                    b.Property<Guid>("LootAwardId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PlusOneState")
                        .HasColumnType("integer");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("LootAwardId");

                    b.ToTable("LootRolls");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("Members");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.RaidEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RhEventId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("WclReportCode")
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RhEventId")
                        .IsUnique();

                    b.HasIndex("WclReportCode")
                        .IsUnique();

                    b.ToTable("RaidEvents");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.AttendanceRecord", b =>
                {
                    b.HasOne("WoobackVash.Api.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoobackVash.Api.Models.RaidEvent", "RaidEvent")
                        .WithMany("Attendance")
                        .HasForeignKey("RaidEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("RaidEvent");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.BoardLayout", b =>
                {
                    b.HasOne("WoobackVash.Api.Models.RaidEvent", "RaidEvent")
                        .WithMany("BoardLayouts")
                        .HasForeignKey("RaidEventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RaidEvent");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.Character", b =>
                {
                    b.HasOne("WoobackVash.Api.Models.Member", "Member")
                        .WithMany("Characters")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Member");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.CharacterGearSnapshot", b =>
                {
                    b.HasOne("WoobackVash.Api.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoobackVash.Api.Models.RaidEvent", "RaidEvent")
                        .WithMany()
                        .HasForeignKey("RaidEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Character");

                    b.Navigation("RaidEvent");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.LootAward", b =>
                {
                    b.HasOne("WoobackVash.Api.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WoobackVash.Api.Models.RaidEvent", "RaidEvent")
                        .WithMany("LootAwards")
                        .HasForeignKey("RaidEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Character");

                    b.Navigation("RaidEvent");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.LootRoll", b =>
                {
                    b.HasOne("WoobackVash.Api.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WoobackVash.Api.Models.LootAward", "LootAward")
                        .WithMany("Rolls")
                        .HasForeignKey("LootAwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("LootAward");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.LootAward", b =>
                {
                    b.Navigation("Rolls");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.Member", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("WoobackVash.Api.Models.RaidEvent", b =>
                {
                    b.Navigation("Attendance");

                    b.Navigation("BoardLayouts");

                    b.Navigation("LootAwards");
                });
#pragma warning restore 612, 618
        }
    }
}
