# fly.toml app configuration file generated for wooback-vash-api on 2026-07-20T16:27:04+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wooback-vash-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpus = 1
  memory_mb = 512
